### ISSUE TITLE
IPC: error when publishing to MQTT

### ISSUE THREAD

**Issue by PierluigiGreto** [aws-greengrass/aws-greengrass-nucleus#1009]
**Describe the bug**
After the update from nucleus 2.1.0 to 2.2.0 sometime when we try to publish we receive this exception:

```
Traceback (most recent call last):    
  File "/greengrass/v2/packages/artifacts-unarchived/heartbeat/99.0.0/component/base/aws.py", line 91, in publish                                                                                                                       
    future.result(self.cfg['mqtt_timeout'])                                                                            
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 432, in result                                           
    return self.__get_result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result                                     
    raise self._exception                          
  File "/usr/local/lib/python3.7/dist-packages/awsiot/eventstreamrpc.py", line 714, in _on_continuation_message        
    raise shape
awsiot.greengrasscoreipc.model.ServiceError
```

**To Reproduce**
I'm not sure. Same environment works if we are using version 2.1.0

**Expected behavior**
Publishing to MQTT

**Actual behavior**
Exception awsiot.greengrasscoreipc.model.ServiceError

**Environment**
 - OS: Raspian 5.4.83-v7+
 - JDK version: .8.0_212-8u212-b01-1+rpi1-b01
 - Nucleus version: 2.2.0

**Comment by MikeDombo** [comment]
Hello Pierluigi,
Thank you for reaching out. The error should contain a message which tells you what the issue is.
The error will also be logged into the greengrass log file. Please provide the log file contents or have a look yourself so that we can help out more.

**Comment by MikeDombo** [comment]
Closing for inactivity. Please reopen if/when you have the requested artifacts
