### ISSUE TITLE
(com.aws.greengrass.lifecyclemanager.UpdateSystemPolicyService): service-update-action-error

### ISSUE THREAD

**Issue by DeboBurro** [aws-greengrass/aws-greengrass-nucleus#1023]
**Describe the bug**
After I deployed a component to target device, the `greengrass.log` shows the folloing error message.
```
2021-07-09T13:20:59.031Z [INFO] (pool-2-thread-18) com.aws.greengrass.deployment.bootstrap.BootstrapManager: Bootstrap task list is saved to file. {filePath=/greengrass/v2/deployments/arn.aws.gree[1/1995]
s-west-2.011715402690.configuration.thinggroup+all-burros.18/bootstrap_task.json}                                                                                                                           
2021-07-09T13:20:59.031Z [INFO] (pool-2-thread-18) com.aws.greengrass.lifecyclemanager.KernelAlternatives: Setting up launch directory for new Nucleus. {}
2021-07-09T13:20:59.033Z [INFO] (pool-2-thread-18) com.aws.greengrass.lifecyclemanager.KernelAlternatives: Finish setup of launch directory for new Nucleus. {}
2021-07-09T13:20:59.033Z [INFO] (pool-2-thread-18) com.aws.greengrass.deployment.bootstrap.BootstrapManager: Execute component bootstrap step. {componentName=burro-dev-deployer}
2021-07-09T13:20:59.039Z [INFO] (Serialized listener processor) com.aws.greengrass.logmanager.LogManagerService: Process LogManager configuration for Greengrass user component. {componentName=burro-dev-de
ployer, serviceName=aws.greengrass.LogManager, currentState=FINISHED}
2021-07-09T13:20:59.039Z [INFO] (pool-2-thread-10) com.aws.greengrass.logmanager.LogManagerService: Starting space management thread. {serviceName=aws.greengrass.LogManager, currentState=FINISHED}
2021-07-09T13:20:59.039Z [INFO] (Serialized listener processor) com.aws.greengrass.logmanager.LogManagerService: Process LogManager configuration for Greengrass system logs. {serviceName=aws.greengrass.Lo
gManager, currentState=FINISHED}
2021-07-09T13:20:59.039Z [INFO] (Serialized listener processor) com.aws.greengrass.logmanager.LogManagerService: Finished processing LogManager configuration. {serviceName=aws.greengrass.LogManager, curre
ntState=FINISHED}
2021-07-09T13:20:59.041Z [INFO] (DeploymentService-lifecycle) com.aws.greengrass.logmanager.LogManagerService: Starting space management thread. {serviceName=aws.greengrass.LogManager, currentState=FINISH
ED}
2021-07-09T13:20:59.041Z [INFO] (Serialized listener processor) com.aws.greengrass.logmanager.LogManagerService: Process LogManager configuration for Greengrass user component. {componentName=burro-dev-de
ployer, serviceName=aws.greengrass.LogManager, currentState=FINISHED}
2021-07-09T13:20:59.041Z [ERROR] (pool-2-thread-22) com.aws.greengrass.logmanager.LogManagerService: Log Space management interrupted. Returning.. {serviceName=aws.greengrass.LogManager, currentState=FINI
SHED}
2021-07-09T13:20:59.041Z [ERROR] (pool-2-thread-24) com.aws.greengrass.logmanager.LogManagerService: Log Space management interrupted. Returning.. {serviceName=aws.greengrass.LogManager, currentState=FINI
SHED}
2021-07-09T13:20:59.041Z [INFO] (Serialized listener processor) com.aws.greengrass.logmanager.LogManagerService: Process LogManager configuration for Greengrass system logs. {serviceName=aws.greengrass.Lo
gManager, currentState=FINISHED}
2021-07-09T13:20:59.041Z [INFO] (Serialized listener processor) com.aws.greengrass.logmanager.LogManagerService: Finished processing LogManager configuration. {serviceName=aws.greengrass.LogManager, curre
ntState=FINISHED}
2021-07-09T13:20:59.042Z [INFO] (pool-2-thread-24) com.aws.greengrass.logmanager.LogManagerService: Starting space management thread. {serviceName=aws.greengrass.LogManager, currentState=FINISHED}
2021-07-09T13:20:59.042Z [INFO] (Serialized listener processor) com.aws.greengrass.lifecyclemanager.GenericExternalService: Setting up dependencies again aws.greengrass.Cli,ros-melodic-spatio,FleetStatusS
ervice:HARD,burro-dev-deployer,DeploymentService:HARD,aws.greengrass.LogManager,formant-script,burro-configurator,TelemetryAgent:HARD,aws.greengrass.Nucleus,UpdateSystemPolicyService:HARD. {serviceName=ma
in, currentState=FINISHED}
2021-07-09T13:20:59.042Z [ERROR] (DeploymentService-lifecycle) com.aws.greengrass.logmanager.LogManagerService: Log Space management interrupted. Returning.. {serviceName=aws.greengrass.LogManager, curren
tState=FINISHED}
2021-07-09T13:20:59.043Z [INFO] (Serialized listener processor) com.aws.greengrass.lifecyclemanager.GenericExternalService: service-config-change. Requesting restart for component. {configNode=services.ma
in.lifecycle, serviceName=main, currentState=FINISHED}
2021-07-09T13:20:59.051Z [ERROR] (pool-2-thread-10) com.aws.greengrass.logmanager.LogManagerService: Log Space management interrupted. Returning.. {serviceName=aws.greengrass.LogManager, currentState=FINI
SHED}
2021-07-09T13:20:59.055Z [INFO] (pool-2-thread-18) com.aws.greengrass.util.platforms.Platform: Killing child processes of pid 30227, force is false. {}
2021-07-09T13:20:59.126Z [INFO] (pool-2-thread-18) com.aws.greengrass.util.platforms.Platform: Killing child processes of pid 30227, force is true. {}
2021-07-09T13:20:59.135Z [ERROR] (pool-2-thread-18) com.aws.greengrass.lifecyclemanager.UpdateSystemPolicyService: service-update-action-error. {action=arn:aws:greengrass:us-west-2:12345678901:configurat
ion:thinggroup/all-burros:18, serviceName=UpdateSystemPolicyService, currentState=FINISHED}
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
        at com.aws.greengrass.lifecyclemanager.GenericExternalService.bootstrap(GenericExternalService.java:190)
        at com.aws.greengrass.deployment.bootstrap.BootstrapManager.executeOneBootstrapTask(BootstrapManager.java:399)
        at com.aws.greengrass.deployment.bootstrap.BootstrapManager.executeAllBootstrapTasksSequentially(BootstrapManager.java:425)
        at com.aws.greengrass.deployment.activator.KernelUpdateActivator.activate(KernelUpdateActivator.java:84)
        at com.aws.greengrass.deployment.DeploymentConfigMerger.updateActionForDeployment(DeploymentConfigMerger.java:150)
        at com.aws.greengrass.deployment.DeploymentConfigMerger.lambda$mergeInNewConfig$0(DeploymentConfigMerger.java:102)
        at com.aws.greengrass.lifecyclemanager.UpdateSystemPolicyService.runUpdateActions(UpdateSystemPolicyService.java:95)
        at com.aws.greengrass.lifecyclemanager.UpdateSystemPolicyService.lambda$startup$0(UpdateSystemPolicyService.java:166)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

2021-07-09T13:20:59.136Z [INFO] (pool-2-thread-18) com.aws.greengrass.lifecyclemanager.UpdateSystemPolicyService: service-update-finish. {serviceName=UpdateSystemPolicyService, currentState=FINISHED}
```

**To Reproduce**
1. Create a role and download a pair of AWS credential `AWS_ACCESS_KEY_ID` and `AWS_SECRET_KEY`. And set them as environment variable.
2. Download the greengrass core and unzip it by   
```
curl -s https://d2s8p88vqu9w66.cloudfront.net/releases/greengrass-nucleus-latest.zip > greengrass-nucleus-latest.zip
unzip greengrass-nucleus-latest.zip -d GreengrassCore && rm greengrass-nucleus-latest.zip
```
3. Install the greengrass core as a system service by  
```
sudo -E java -Droot="/greengrass/v2" -Dlog.store=FILE -jar ./GreengrassCore/lib/Greengrass.jar --aws-region us-west-2 --thing-name $HOSTNAME  --component-default-user $USER:docker --provision true --setup-system-service true --deploy-dev-tools true
```
4. Create a component to deploy on the target device from another computer.
5. Type `sudo cat /greengrass/v2/logs/greengrass.log` to see the log.

**Expected behavior**
I expect that the log manager would not be interrupted.
All the logs from all the devices should be uploaded to cloudWatch.

**Actual behavior**
Somehow, I only got partial logs from some of the devices on the cloudWatch.
Also the deployment failed but not sure if this is relevant.

**Environment**
 - OS: Ubuntu 18.04
 - JDK version: Java 8
 - Nucleus version: 2.3.0

**Additional context**
Not sure what the interesting log means here.
```
2021-07-09T13:20:59.055Z [INFO] (pool-2-thread-18) com.aws.greengrass.util.platforms.Platform: Killing child processes of pid 30227, force is false. {}                                                     
2021-07-09T13:20:59.126Z [INFO] (pool-2-thread-18) com.aws.greengrass.util.platforms.Platform: Killing child processes of pid 30227, force is true. {}  
```

**Comment by MikeDombo** [comment]
Log manager shutting down is appropriate because the deployment is causing Greengrass to restart.


Reference for the error at the end: https://github.com/aws-greengrass/aws-greengrass-nucleus/blob/1fd760b21cfaa420ed07d24af7eade478011f8bc/src/main/java/com/aws/greengrass/lifecyclemanager/GenericExternalService.java#L189-L191

**Comment by MikeDombo** [comment]
What precisely are you deploying? Provide the list components your are deploying along with their recipes and configuration.

**Comment by MikeDombo** [comment]
Log manager only uploads logs after they have rotated. Logs rotate based on time (once per hour) or based the size of the file. Most of what you're seeing is expected behavior.

**Comment by DeboBurro** [comment]
Thanks, I just saw the timeout is a string in `burro-dev-deployer` component.
The job configuration.
```

{
  "deploymentId": "d4c1ccd9-2b2d-4d16-9d5c-300f7f35ebe5",
  "schemaDate": "2021-05-17",
  "deploymentName": "Deployment for all burros (phase 1)",
  "configurationArn": "arn:aws:greengrass:$AREA:$ACCOUNT_NUMBER:configuration:thinggroup/all-burros:18",
  "creationTimestamp": 1625836341225,
  "components": {
    "ros-melodic-spatio": {
      "version": "1.0.0",
      "runWith": {
        "posixUser": "root:root"
      }
    },
    "burro-dev-deployer": {
      "version": "2.6.3",
      "configurationUpdate": {
        "reset": [
          ""
        ]
      }
    },
    "aws.greengrass.LogManager": {
      "version": "2.1.2",
      "configurationUpdate": {
        "merge": {
          "logsUploaderConfiguration": {
            "systemLogsConfiguration": {
              "uploadToCloudWatch": "true",
              "minimumLogLevel": "INFO",
              "diskSpaceLimit": "10",
              "diskSpaceLimitUnit": "MB",
              "deleteLogFileAfterCloudUpload": "false"
            },
            "componentLogsConfiguration": [
              {
                "componentName": "burro-dev-deployer",
                "minimumLogLevel": "INFO",
                "diskSpaceLimit": "10",
                "diskSpaceLimitUnit": "MB",
                "deleteLogFileAfterCloudUpload": "false"
              }
            ]
          },
          "periodicUploadIntervalSec": "60"
        },
        "reset": [
          ""
        ]
      }
    },
    "formant-script": {
      "version": "1.0.1",
      "runWith": {
        "posixUser": "root:root"
      }
    }
  },
  "failureHandlingPolicy": "ROLLBACK",
  "requiredCapabilities": [],
  "componentUpdatePolicy": {
    "timeout": 10,
    "action": "NOTIFY_COMPONENTS"
  },
  "configurationValidationPolicy": {
    "timeout": 1
  }
}
```

The components we deployed as shown below.
```
{
  "RecipeFormatVersion": "2020-01-25",
  "ComponentName": "ros-melodic-spatio",
  "ComponentVersion": "1.0.0",
  "ComponentType": "aws.greengrass.generic",
  "ComponentDescription": "A component that wipe out everything but executables.",
  "ComponentPublisher": "Company name",
  "Manifests": [
    {
      "Platform": {
        "os": "linux"
      },
      "Lifecycle": {
        "Bootstrap": {
          "Script": "/bin/bash {artifacts:path}/ros-melodic-spatio.bash",
          "Timeout": 18000
        }
      },
      "Artifacts": [
        {
          "Uri": "s3://burro-script/artifacts/ros-melodic-spatio/1.0.0/ros-melodic-spatio.bash",
          "Digest": "/GHiH8yJnV9yKlrmBi8K5tM6yXbstHrDMofdfK3BGdk=",
          "Algorithm": "SHA-256",
          "Unarchive": "NONE",
          "Permission": {
            "Read": "ALL",
            "Execute": "ALL"
          }
        }
      ]
    }
  ],
  "Lifecycle": {}
}
```

```
{
  "RecipeFormatVersion": "2020-01-25",
  "ComponentName": "formant-script",
  "ComponentVersion": "1.0.1",
  "ComponentType": "aws.greengrass.generic",
  "ComponentDescription": "A component that wipe out everything but executables.",
  "ComponentPublisher": "Company name",
  "Manifests": [
    {
      "Platform": {
        "os": "linux"
      },
      "Lifecycle": {
        "Bootstrap": {
          "Script": "/bin/bash {artifacts:path}/formant-script.bash",
          "Timeout": 18000
        }
      },
      "Artifacts": [
        {
          "Uri": "s3://burro-script/artifacts/formant-script/1.0.1/formant-script.bash",
          "Digest": "aIqRufHWw4Ha19sz06sup8b9RAidIaK54MX+j2haqo8=",
          "Algorithm": "SHA-256",
          "Unarchive": "NONE",
          "Permission": {
            "Read": "ALL",
            "Execute": "ALL"
          }
        }
      ]
    }
  ],
  "Lifecycle": {}
}
```

```
{
  "RecipeFormatVersion": "2020-01-25",
  "ComponentName": "burro-dev-deployer",
  "ComponentVersion": "2.6.3",
  "ComponentType": "aws.greengrass.generic",
  "ComponentDescription": "Update software version to 2.6.3",
  "ComponentPublisher": "Company name",
  "Manifests": [
    {
      "Platform": {
        "os": "linux"
      },
      "Lifecycle": {
        "Bootstrap": {
          "Script": "/bin/bash -c  \"/bin/bash {artifacts:path}/burro-dev-deployer.bash\"",
          "Timeout": "18000"
        }
      },
      "Artifacts": [
        {
          "Uri": "s3://burro-script/artifacts/burro-dev-deployer/2.6.3/burro-dev-deployer.bash",
          "Digest": "4s5kYna9lfRenF8aR5WZr7TcMNNvaTVCVcapnn6ByME=",
          "Algorithm": "SHA-256",
          "Unarchive": "NONE",
          "Permission": {
            "Read": "ALL",
            "Execute": "ALL"
          }
        }
      ]
    }
  ],
  "Lifecycle": {}
}
```

**Comment by MikeDombo** [comment]
Please change the timeout to be an integer. That will fix the issue.

However, I do not think that you should be using `bootstrap`. What are you using it for? Typically you should be using `run` or `install`.
Bootstrap has a very specific use case which it is unlikely that you need it. Bootstrap should only be used when you need to restart Greengrass or the device after running the bootstrap script.


In order to run a script as root use `requiresPrivilege: true` instead of overriding the runwith user to be root. Have a look at https://docs.aws.amazon.com/greengrass/v2/developerguide/component-recipe-reference.html

**Comment by DeboBurro** [comment]
Is there any difference between `requiresPrivilege: true` and `runwith : { posixUser : { root: root } } `?
Also we use the bootstrap to run a script to rsync files from a server when the component version changes. Is that going to affect the deployments?
In this case, should we use `Install` to rsync a folder from a server when the component version changes, or should we create a new component to run `install`?

**Comment by MikeDombo** [comment]
No, there isn't much difference, but using requires privilege is more correct and is portable across systems.

You should be using install. If you really want to be Greengrass-y then you'd use our artifacts which download from S3, but rsycing during install also works.

**Comment by DeboBurro** [comment]
The log shown above is one of the deployments. Not sure if the following questions are relevant to the error log above. Thank you so much for your help in advance.
1. I am wondering if two deployments happened at same time from two `thing-group`s, would one effect the other one?
2. If the group deployment be modified several times by keeping adding new components, when a new `thing` be added to the thing-group, will it receive the components and execute the `bootstrap` scripts in order?
3. On the other hand, would all the components deployed from the `abc-thing-group` be removed when I remove a `thing` from the `abc-thing-group` when the device is using Greengrass core software version 2.2.0?

**Comment by MikeDombo** [comment]
1. Deployments from separate groups do not affect each other except that they may overwrite configuration if multiple groups are configuring the same component.
2. When a thing is added into a group it will receive the latest deployment which was targeting that group. The bootstrap steps are not executed in any particular order.
3. Components are not currently removed when you remove a thing from a group, this feature is coming in a future version.
