### ISSUE TITLE
greengrass Nucleus Install : Fails to setup on Windows 10

### ISSUE THREAD

**Issue by adomigar** [aws-greengrass/aws-greengrass-nucleus#1165]
**Describe the bug**

Hi there,
I have a problem when I am installing the AWS Greengrass package on a Windows 10 OS. I have followed all the steps provided by the AWS Greengrass set-up webpage, but unfortunatelly, it does not work.

The set-up command I am writing:
`java "-Droot=C:\greengrass\v2" "-Dlog.store=FILE" -jar .\lib\Greengrass.jar --init-config .\config-CoreDevice01.yaml --component-default-user ggc_user --setup-system-service true`

**The output from the program:**
```
Error while trying to setup Greengrass Nucleus
java.lang.RuntimeException: Cannot create all required directories
        at com.aws.greengrass.lifecyclemanager.KernelCommandLine.initPaths(KernelCommandLine.java:191)
        at com.aws.greengrass.lifecyclemanager.KernelCommandLine.lambda$parseArgs$0(KernelCommandLine.java:147)
        at com.aws.greengrass.config.Topic.subscribe(Topic.java:50)
        at com.aws.greengrass.lifecyclemanager.KernelCommandLine.parseArgs(KernelCommandLine.java:147)
        at com.aws.greengrass.lifecyclemanager.Kernel.parseArgs(Kernel.java:591)
        at com.aws.greengrass.easysetup.GreengrassSetup.performSetup(GreengrassSetup.java:296)
        at com.aws.greengrass.easysetup.GreengrassSetup.main(GreengrassSetup.java:269)
Caused by: java.nio.file.attribute.UserPrincipalNotFoundException
        at java.base/sun.nio.fs.WindowsUserPrincipals.lookup(WindowsUserPrincipals.java:147)
        at java.base/sun.nio.fs.WindowsFileSystem$LookupService$1.lookupPrincipalByGroupName(WindowsFileSystem.java:250)
        at com.aws.greengrass.util.platforms.windows.WindowsPlatform$WindowsFileSystemPermissionView.aclEntries(WindowsPlatform.java:413)
        at com.aws.greengrass.util.platforms.windows.WindowsPlatform$WindowsFileSystemPermissionView.<init>(WindowsPlatform.java:326)
        at com.aws.greengrass.util.platforms.windows.WindowsPlatform.getFileSystemPermissionView(WindowsPlatform.java:458)
        at com.aws.greengrass.util.platforms.Platform.setPermissions(Platform.java:167)
        at com.aws.greengrass.util.platforms.Platform.setPermissions(Platform.java:129)
        at com.aws.greengrass.util.Permissions.setRootPermission(Permissions.java:93)
        at com.aws.greengrass.util.NucleusPaths.setRootPath(NucleusPaths.java:99)
        at com.aws.greengrass.lifecyclemanager.KernelCommandLine.initPaths(KernelCommandLine.java:170)
```

**The yaml file:**
---
system:
  certificateFilePath: "C:\greengrass\v2\X.cert.pem"
  privateKeyPath: "C:\greengrass\v2\Y.private.key"
  rootCaPath: "C:\greengrass\v2\AmazonRootCA1.pem"
  rootpath: "C:\greengrass\v2"
  thingName: "co2sink-dev-CoreDevice01"
services:
  aws.greengrass.Nucleus:
    componentType: "NUCLEUS"
    version: "2.5.2"
    configuration:
      awsRegion: "eu-west-1"
      iotRoleAlias: "co2sink-dev-TokenExchangeRoleAlias"
      iotDataEndpoint: "aa598pljtwur1-ats.iot.eu-west-1.amazonaws.com"
      iotCredEndpoint: "cszj6chx6z301.credentials.iot.eu-west-1.amazonaws.com"

**To Reproduce**
`java "-Droot=C:\greengrass\v2" "-Dlog.store=FILE" -jar .\lib\Greengrass.jar --init-config .\config-CoreDevice01.yaml --component-default-user ggc_user --setup-system-service true`

**Expected behavior**
Setup Greengrass Nucleus on Windows 10

**Actual behavior**
Error while trying to setup Greengrass Nucleus

**Environment**
 - OS: Windows 10
 - Nucleus version: latest

**Comment by dpergarc** [comment]
The same issue here, but I have not found any solution yet :(

**Comment by MikeDombo** [comment]
Hi @dpergarc and @adomigar,
This issue happens when you are running Greengrass on Windows which is setup in a non-English language. It has already been fixed by us, but not yet released. You may work around the issue by building the Nucleus from the `main` branch here, or you can change the Windows language to English. 

We'll work to release this fix soon.

Thank you

**Comment by christiantobin** [comment]
I am getting this issue on Mac

**Comment by MikeDombo** [comment]
@christiantobin Hello, Greengrass has no official Mac support. Please use a supporter OS either Windows or Linux.
