### ISSUE TITLE
(nucleus): restart autossh will report fail state

### ISSUE THREAD

**Issue by DeboBurro** [aws-greengrass/aws-greengrass-nucleus#1266]
**Describe the bug**
If autossh system service be restarted, the greengrass deployment would fail.
 
**To Reproduce**
1. Create a component that would 
    a. find the autossh service file difference, if any, replace autossh service with a new autossh service file, reload and restart the autossh system service
    b. do some other system configuration settings
2. Deploy the component to a computer using Ubuntu 18.04, 20.04
3. It will finish step 1-a  and report deployment failed state.

**Expected behavior**
I am expecting the greengrass would later go through the step 1-b

**Actual behavior**
It finished the step 1-a

**Environment**
 - OS:  Ubuntu 18.04, 20.04
 - JDK version: java 8
 - Nucleus version: 2.6.0

**Additional context**
Impact of the behavior: I need to deploy twice to make it go through.

**Comment by MikeDombo** [comment]
Hi, 

Why does the deployment fail? Deployments can fail for many reasons, but in this case it sounds like it would fail because the component that you wrote entered the "BROKEN" state, is that correct?

If your component is becoming BROKEN, then the simple solution is for your component to _not_ break, but handle errors and retries itself.

**Comment by DeboBurro** [comment]
The burro-configurator component log as shown below. After it replaced and restarted the autossh at 22:06:41, the deployment shows failed state. How to tell if it's in so called  'BROKEN' state?
```
2022-07-18T22:06:38.591Z [INFO] (pool-2-thread-16) burro-configurator: shell-runner-start. {scriptName=services.burro-configurator.lifecycle.Bootstrap.Script, serviceName=burro-configurator, currentState=NEW, command=["/bin/bash /greengrass/v2/packages/artifacts-unarchived/burro-configurator/3.5...."]}
2022-07-18T22:06:40.521Z [INFO] (Copier) burro-configurator: stdout. Start to check the autossh system service. {scriptName=services.burro-configurator.lifecycle.Bootstrap.Script, serviceName=burro-configurator, currentState=NEW}
2022-07-18T22:06:40.528Z [INFO] (Copier) burro-configurator: stdout. extracted numbers from the hostname is 7001. {scriptName=services.burro-configurator.lifecycle.Bootstrap.Script, serviceName=burro-configurator, currentState=NEW}
2022-07-18T22:06:40.531Z [WARN] (Copier) burro-configurator: stderr. /greengrass/v2/packages/artifacts-unarchived/burro-configurator/3.5.8/burro-configurator/provision_scripts/autossh.bash: line 51: 3a4: command not found. {scriptName=services.burro-configurator.lifecycle.Bootstrap.Script, serviceName=burro-configurator, currentState=NEW}
2022-07-18T22:06:40.531Z [INFO] (Copier) burro-configurator: stdout. Detected difference between autossh service files, going to replace. {scriptName=services.burro-configurator.lifecycle.Bootstrap.Script, serviceName=burro-configurator, currentState=NEW}
2022-07-18T22:06:41.051Z [INFO] (Copier) burro-configurator: stdout. Done replacing autossh service with the latest one. {scriptName=services.burro-configurator.lifecycle.Bootstrap.Script, serviceName=burro-configurator, currentState=NEW}
```

In the mean time, the greengrass log
```
2022-07-18T22:06:38.569Z [INFO] (pool-2-thread-16) com.aws.greengrass.lifecyclemanager.KernelAlternatives: Setting up launch directory for new Nucleus. {}
2022-07-18T22:06:38.571Z [INFO] (pool-2-thread-16) com.aws.greengrass.lifecyclemanager.KernelAlternatives: Finished setup of launch directory for new Nucleus. {}
2022-07-18T22:06:38.571Z [INFO] (pool-2-thread-16) com.aws.greengrass.deployment.bootstrap.BootstrapManager: Execute component bootstrap step. {componentName=aws-credentials-adder}
2022-07-18T22:06:38.584Z [INFO] (pool-2-thread-16) com.aws.greengrass.deployment.bootstrap.BootstrapManager: Saving bootstrap task list to file. {filePath=/greengrass/v2/deployments/532e35e6-0934-4814-8aaf-ee8fae85a53e/bootstrap_task.json}
2022-07-18T22:06:38.587Z [INFO] (pool-2-thread-16) com.aws.greengrass.deployment.bootstrap.BootstrapManager: Bootstrap task list is saved to file. {filePath=/greengrass/v2/deployments/532e35e6-0934-4814-8aaf-ee8fae85a53e/bootstrap_task.json}
2022-07-18T22:06:38.587Z [INFO] (pool-2-thread-16) com.aws.greengrass.deployment.bootstrap.BootstrapManager: Execute component bootstrap step. {componentName=burro-configurator}
2022-07-18T22:06:41.052Z [INFO] (pool-2-thread-16) com.aws.greengrass.deployment.bootstrap.BootstrapManager: Saving bootstrap task list to file. {filePath=/greengrass/v2/deployments/532e35e6-0934-4814-8aaf-ee8fae85a53e/bootstrap_task.json}
2022-07-18T22:06:41.064Z [INFO] (pool-2-thread-16) com.aws.greengrass.deployment.bootstrap.BootstrapManager: Bootstrap task list is saved to file. {filePath=/greengrass/v2/deployments/532e35e6-0934-4814-8aaf-ee8fae85a53e/bootstrap_task.json}
2022-07-18T22:06:41.064Z [INFO] (pool-2-thread-16) com.aws.greengrass.deployment.activator.DeploymentActivator: merge-config. Rolling back failed deployment. {deploymentId=532e35e6-0934-4814-8aaf-ee8fae85a53e}
com.aws.greengrass.deployment.exceptions.ServiceUpdateException: Fail to execute bootstrap step for burro-configurator, exit code: 1
        at com.aws.greengrass.deployment.bootstrap.BootstrapManager.executeAllBootstrapTasksSequentially(BootstrapManager.java:435)
        at com.aws.greengrass.deployment.activator.KernelUpdateActivator.activate(KernelUpdateActivator.java:84)
        at com.aws.greengrass.deployment.DeploymentConfigMerger.updateActionForDeployment(DeploymentConfigMerger.java:150)
        at com.aws.greengrass.deployment.DeploymentConfigMerger.lambda$mergeInNewConfig$0(DeploymentConfigMerger.java:102)
        at com.aws.greengrass.lifecyclemanager.UpdateSystemPolicyService.runUpdateActions(UpdateSystemPolicyService.java:95)
        at com.aws.greengrass.lifecyclemanager.UpdateSystemPolicyService.lambda$startup$0(UpdateSystemPolicyService.java:165)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)

2022-07-18T22:06:41.065Z [INFO] (pool-2-thread-16) com.aws.greengrass.deployment.DeploymentDirectoryManager: Persist deployment metadata. {file=/greengrass/v2/deployments/532e35e6-0934-4814-8aaf-ee8fae85a53e/deployment_metadata.json, deploymentId=532e35e6-0934-4814-8aaf-ee8fae85a53e}
2022-07-18T22:06:41.071Z [INFO] (pool-2-thread-16) com.aws.greengrass.lifecyclemanager.KernelLifecycle: system-shutdown. {main=services.main:FINISHED}
2022-07-18T22:06:41.077Z [INFO] (pool-2-thread-16) com.aws.greengrass.lifecyclemanager.Kernel: effective-config-dump-complete. {file=/greengrass/v2/config/effectiveConfig.yaml}
2022-07-18T22:06:41.077Z [INFO] (pool-2-thread-3) com.aws.greengrass.lifecyclemanager.GenericExternalService: service-close. Service is now closing. {serviceName=main, currentState=FINISHED}
2022-07-18T22:06:41.077Z [INFO] (pool-2-thread-13) com.aws.greengrass.status.FleetStatusService: service-close. Service is now closing. {serviceName=FleetStatusService, currentState=FINISHED}
2022-07-18T22:06:41.077Z [INFO] (pool-2-thread-18) com.aws.greengrass.lifecyclemanager.UpdateSystemPolicyService: service-close. Service is now closing. {serviceName=UpdateSystemPolicyService, currentState=FINISHED}
2022-07-18T22:06:41.077Z [INFO] (pool-2-thread-20) com.aws.greengrass.deployment.DeploymentService: service-close. Service is now closing. {serviceName=DeploymentService, currentState=FINISHED}
2022-07-18T22:06:41.077Z [INFO] (pool-2-thread-3) com.aws.greengrass.lifecyclemanager.GenericExternalService: service-close. Service is now closing. {serviceName=burro-configurator, currentState=NEW}
2022-07-18T22:06:41.077Z [INFO] (pool-2-thread-13) com.aws.greengrass.lifecyclemanager.GenericExternalService: service-close. Service is now closing. {serviceName=aws.greengrass.Nucleus, currentState=FINISHED}
2022-07-18T22:06:41.078Z [INFO] (pool-2-thread-20) com.aws.greengrass.telemetry.TelemetryAgent: service-close. Service is now closing. {serviceName=TelemetryAgent, currentState=FINISHED}
2022-07-18T22:06:41.078Z [INFO] (pool-2-thread-16) com.aws.greengrass.lifecyclemanager.KernelLifecycle: Waiting for services to shutdown. {}
2022-07-18T22:06:41.078Z [INFO] (pool-2-thread-18) com.aws.greengrass.lifecyclemanager.GenericExternalService: service-close. Service is now closing. {serviceName=aws-credentials-adder, currentState=NEW}
2022-07-18T22:06:41.078Z [INFO] (pool-2-thread-16) com.aws.greengrass.lifecyclemanager.KernelLifecycle: Waiting for executors to shutdown. {}
2022-07-18T22:06:41.079Z [WARN] (pool-2-thread-10) com.aws.greengrass.mqttclient.MqttClient: Shutting down spooler task. {}
2022-07-18T22:06:41.079Z [INFO] (Serialized listener processor) com.aws.greengrass.lifecyclemanager.KernelLifecycle: executor-service-shutdown-initiated. {}
2022-07-18T22:06:41.079Z [INFO] (pool-2-thread-15) com.aws.greengrass.deployment.DeploymentService: deployment-task-execution. Cancelled deployment merge future due to interrupt, update may not get cancelled if it is already being applied. {deploymentId=532e35e6-0934-4814-8aaf-ee8fae85a53e, serviceName=DeploymentService, currentState=FINISHED}
2022-07-18T22:07:11.079Z [INFO] (pool-2-thread-16) com.aws.greengrass.lifecyclemanager.KernelLifecycle: executor-service-shutdown-complete. {executor-terminated=false, scheduled-executor-terminated=true}
2022-07-18T22:07:11.081Z [INFO] (pool-2-thread-16) com.aws.greengrass.lifecyclemanager.KernelLifecycle: context-shutdown-initiated. {}
2022-07-18T22:07:11.086Z [INFO] (Thread-3) com.aws.greengrass.mqttclient.AwsIotMqttClient: Connection purposefully interrupted. {clientId=burro-7-001}
2022-07-18T22:07:11.086Z [ERROR] (pool-2-thread-16) com.aws.greengrass.mqttclient.AwsIotMqttClient: Error while disconnecting the MQTT client. {clientId=burro-7-001}
java.lang.InterruptedException
        at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:385)
        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2022)
        at com.aws.greengrass.mqttclient.AwsIotMqttClient.close(AwsIotMqttClient.java:409)
        at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:807)
        at com.aws.greengrass.mqttclient.MqttClient.close(MqttClient.java:781)
        at com.aws.greengrass.dependency.Context.lambda$shutdown$4(Context.java:209)
        at java.base/java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4772)
        at com.aws.greengrass.dependency.Context.shutdown(Context.java:205)
        at com.aws.greengrass.dependency.Context.close(Context.java:229)
        at com.aws.greengrass.lifecyclemanager.KernelLifecycle.shutdown(KernelLifecycle.java:525)
        at com.aws.greengrass.lifecyclemanager.KernelLifecycle.shutdown(KernelLifecycle.java:485)
        at com.aws.greengrass.lifecyclemanager.Kernel.shutdown(Kernel.java:266)
        at com.aws.greengrass.deployment.activator.KernelUpdateActivator.rollback(KernelUpdateActivator.java:117)
        at com.aws.greengrass.deployment.activator.KernelUpdateActivator.activate(KernelUpdateActivator.java:95)
        at com.aws.greengrass.deployment.DeploymentConfigMerger.updateActionForDeployment(DeploymentConfigMerger.java:150)
        at com.aws.greengrass.deployment.DeploymentConfigMerger.lambda$mergeInNewConfig$0(DeploymentConfigMerger.java:102)
        at com.aws.greengrass.lifecyclemanager.UpdateSystemPolicyService.runUpdateActions(UpdateSystemPolicyService.java:95)
        at com.aws.greengrass.lifecyclemanager.UpdateSystemPolicyService.lambda$startup$0(UpdateSystemPolicyService.java:165)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)

2022-07-18T22:07:11.087Z [INFO] (pool-2-thread-16) com.aws.greengrass.lifecyclemanager.KernelLifecycle: context-shutdown-complete. {}
2022-07-18T22:07:12.375Z [INFO] (main) com.aws.greengrass.util.platforms.Platform: Getting platform instance com.aws.greengrass.util.platforms.unix.linux.LinuxPlatform.. {}
2022-07-18T22:07:12.393Z [INFO] (main) com.aws.greengrass.config.Configuration: config-loading. Read configuration from a file path. {path=/greengrass/v2/deployments/532e35e6-0934-4814-8aaf-ee8fae85a53e/rollback_snapshot.tlog}
2022-07-18T22:07:12.479Z [INFO] (main) com.aws.greengrass.lifecyclemanager.Kernel: effective-config-dump-complete. {file=/greengrass/v2/config/effectiveConfig.yaml}
2022-07-18T22:07:12.564Z [INFO] (main) com.aws.greengrass.lifecyclemanager.Kernel: Resume deployment. {deploymentStage=KERNEL_ROLLBACK}
2022-07-18T22:07:12.565Z [INFO] (main) com.aws.greengrass.deployment.DeploymentDirectoryManager: Load deployment metadata. {file=/greengrass/v2/deployments/532e35e6-0934-4814-8aaf-ee8fae85a53e/deployment_metadata.json}
2022-07-18T22:07:12.588Z [INFO] (main) com.aws.greengrass.lifecyclemanager.KernelLifecycle: system-start. Launch Nucleus. {configPath=/greengrass/v2/config, rootPath=/greengrass/v2, version=2.6.0}
2022-07-18T22:07:12.663Z [INFO] (main) software.amazon.awssdk.eventstreamrpc.RpcServer: IpcServer started.... {}

```

**Comment by MikeDombo** [comment]
OK, so this is easy enough. The deployment failed because `Fail to execute bootstrap step for burro-configurator, exit code: 1`.

So your bootstrap is _failing_ with exit code 1. It needs to not fail.

**Comment by DeboBurro** [comment]
Oh, my bad, didn't notice that.
Thank you Mike.
