### ISSUE TITLE
(LambdaRuntime): Encountered error during attempt to get work

### ISSUE THREAD

**Issue by MartinLoeper** [aws-greengrass/aws-greengrass-nucleus#1468]
**Describe the bug**
I deployed a Lambda function using `aws.greengrass.LambdaManager` and `aws.greengrass.LegacySubscriptionRouter`. When I boot the nucleus and the device has internet access everything works fine. When the device boots and there is no internet connection, I get the error message `Encountered error during attempt to get work: Error: connect ECONNREFUSED 127.0.0.1:35023` and my custom lambda function crashes.

**To Reproduce**
Deploy a Node.js lambda function and start nucleus without internet access.

Node.js Version: v16.14.2

The lambda function was ported from our greengrass v1 deployment.
I do not know what I am missing here...
I do not even know what is supposed to be running on `127.0.0.1:35023`.
The lambda function runs with the following nucleus configuration:

```
Component Name: nesto.driver.StandardPrinter
    Version: 1.0.15-prod
    State: RUNNING
    Configuration: {"containerMode":"NoContainer","containerParams":{"devices":{},"memorySize":16384.0,"mountROSysfs":false,"volumes":{}},"inputPayloadEncodingType":"json","lambdaExecutionParameters":{"EnvironmentVariables":{<REDACTED>},"maxIdleTimeInSeconds":60.0,"maxInstancesCount":100.0,"maxQueueSize":1000.0,"pinned":true,"pubsubTopics":{},"statusTimeoutInSeconds":60.0,"timeoutInSeconds":3.0}
```

It is a long-running lambda function that does not expect to receive any events via its handler.

**Expected behavior**
The lambda function should be able to run even without the device having internet access.

**Actual behavior**
The lambda function crashes with the error message and logs attached below.

**Environment**
 - OS: custom yocto build
 - JDK version: OpenJDK 64-Bit Server VM Corretto-11.0.17.8.1 (build 11.0.17+8-LTS, mixed mode)
 - Nucleus version: 2.9.2

**Additional context**

```
2023-05-19T16:30:09.745Z [ERROR] (pool-2-thread-39) nesto.driver.StandardPrinter: Encountered error during attempt to get work: Error: connect ECONNREFUSED 127.0.0.1:35023. {serviceInstance=0, serviceName=nesto.
driver.StandardPrinter, currentState=RUNNING}
2023-05-19T16:30:09.758Z [ERROR] (pool-2-thread-39) nesto.driver.StandardPrinter: /data/greengrass/v2/packages/artifacts-unarchived/aws.greengrass.LambdaRuntimes/2.0.8/runtime/nodejs/node_modules/aws-greengrass-
common-js/retry.js:94. {serviceInstance=0, serviceName=nesto.driver.StandardPrinter, currentState=RUNNING}
2023-05-19T16:30:09.759Z [ERROR] (pool-2-thread-39) nesto.driver.StandardPrinter:             throw new Error(`Retry handler for ${this._taskName} exceeded max attempt count during retries.`);. {serviceInstance=
0, serviceName=nesto.driver.StandardPrinter, currentState=RUNNING}
2023-05-19T16:30:09.759Z [ERROR] (pool-2-thread-39) nesto.driver.StandardPrinter:             ^. {serviceInstance=0, serviceName=nesto.driver.StandardPrinter, currentState=RUNNING}
2023-05-19T16:30:09.759Z [ERROR] (pool-2-thread-39) nesto.driver.StandardPrinter: {serviceInstance=0, serviceName=nesto.driver.StandardPrinter, currentState=RUNNING}
2023-05-19T16:30:09.760Z [ERROR] (pool-2-thread-39) nesto.driver.StandardPrinter: Error: Retry handler for bound getWork exceeded max attempt count during retries.. {serviceInstance=0, serviceName=nesto.driver.StandardPrinter, currentState=RUNNING}
2023-05-19T16:30:09.760Z [ERROR] (pool-2-thread-39) nesto.driver.StandardPrinter:     at BackoffRetry._retryOrThrowError (/data/greengrass/v2/packages/artifacts-unarchived/aws.greengrass.LambdaRuntimes/2.0.8/runtime/nodejs/node_modules/aws-greengrass-common-js/retry.js:94:19). {serviceInstance=0, serviceName=nesto.driver.StandardPrinter, currentState=RUNNING}
2023-05-19T16:30:09.760Z [ERROR] (pool-2-thread-39) nesto.driver.StandardPrinter:     at wrappedTaskToTryCallback (/data/greengrass/v2/packages/artifacts-unarchived/aws.greengrass.LambdaRuntimes/2.0.8/runtime/nodejs/node_modules/aws-greengrass-common-js/retry.js:52:34). {serviceInstance=0, serviceName=nesto.driver.StandardPrinter, currentState=RUNNING}
2023-05-19T16:30:09.760Z [ERROR] (pool-2-thread-39) nesto.driver.StandardPrinter:     at ClientRequest.<anonymous> (/data/greengrass/v2/packages/artifacts-unarchived/aws.greengrass.LambdaRuntimes/2.0.8/runtime/nodejs/node_modules/aws-greengrass-ipc-sdk-js/ipcclient.js:85:13). {serviceInstance=0, serviceName=nesto.driver.StandardPrinter, currentState=RUNNING}
2023-05-19T16:30:09.760Z [ERROR] (pool-2-thread-39) nesto.driver.StandardPrinter:     at ClientRequest.emit (node:events:526:28). {serviceInstance=0, serviceName=nesto.driver.StandardPrinter, currentState=RUNNING}
2023-05-19T16:30:09.761Z [ERROR] (pool-2-thread-39) nesto.driver.StandardPrinter:     at Socket.socketErrorListener (node:_http_client:442:9). {serviceInstance=0, serviceName=nesto.driver.StandardPrinter, currentState=RUNNING}
2023-05-19T16:30:09.761Z [ERROR] (pool-2-thread-39) nesto.driver.StandardPrinter:     at Socket.emit (node:events:526:28). {serviceInstance=0, serviceName=nesto.driver.StandardPrinter, currentState=RUNNING}
2023-05-19T16:30:09.761Z [ERROR] (pool-2-thread-39) nesto.driver.StandardPrinter:     at emitErrorNT (node:internal/streams/destroy:157:8). {serviceInstance=0, serviceName=nesto.driver.StandardPrinter, currentState=RUNNING}
2023-05-19T16:30:09.761Z [ERROR] (pool-2-thread-39) nesto.driver.StandardPrinter:     at emitErrorCloseNT (node:internal/streams/destroy:122:3). {serviceInstance=0, serviceName=nesto.driver.StandardPrinter, currentState=RUNNING}
2023-05-19T16:30:09.761Z [ERROR] (pool-2-thread-39) nesto.driver.StandardPrinter:     at processTicksAndRejections (node:internal/process/task_queues:83:21). {serviceInstance=0, serviceName=nesto.driver.StandardPrinter, currentState=RUNNING}
```

**Comment by MartinLoeper** [comment]
Hey greengrass team, could you please take a quick look at this one asap? It is currently blocking our rollout for Greengrass V2 devices.

**Comment by shaguptashaikh** [comment]
Hi Martin, I'm looking into this and will post an update shortly

**Comment by shaguptashaikh** [comment]
Hi Martin, in order to investigate this, we'd need more information. Are you able to provide all log files and config files from the root directory, redacting any confidential info? You can also open a support case if it's easier to share this information that way. Thanks

**Comment by MartinLoeper** [comment]
@shaguptashaikh Thanks for looking into it. Just attached all of the logs via aws support.

**Comment by MikeDombo** [comment]
Closing issue here as you say there is an issue open with AWS support now.
