### ISSUE TITLE
(nucleus): error when installing Greengrass with custom provisioning plugin

### ISSUE THREAD

**Issue by vmyron** [aws-greengrass/aws-greengrass-nucleus#1528]
**Describe the bug**
I've developed my custom provisioning plugin and  when I am trying to install Greengrass with this plugin, I've got an error. 
I was strictly following instructions here https://docs.aws.amazon.com/greengrass/v2/developerguide/custom-provisioning.html

**To Reproduce**
- Implement class implementing DeviceIdentityInterface
- Implement method **name()** to return "aws.greengrass.MyCustomProvisioningPlugin"
- config.yaml
```
---
services:
  aws.greengrass.Nucleus:
    version: "2.11.2"
    configuration:

  aws.greengrass.MyCustomProvisioningPlugin:
    configuration:
```
- installation command
```
  java -Droot="C:\Tools\greengrass" "-Dlog.store=FILE" ^
        -jar "C:\Tools\GreengrassInstaller\lib\Greengrass.jar" ^
        --trusted-plugin "C:\Tools\GreengrassPlugins\aws.greengrass.MyCustomProvisioningPlugin.jar" ^
        --init-config "C:\Tools\GreengrassInstaller\config.yaml" ^
        --component-default-user ggc_user ^
        --setup-system-service true
```

**Expected behavior**
Greengrass Cor Software installed successfully with custom provisioning

**Actual behavior**
```
Error while trying to setup Greengrass Nucleus
java.lang.IllegalArgumentException: Can't create instance of com.aws.greengrass.deployment.DeviceConfiguration
        at com.aws.greengrass.dependency.Context$Value.constructObjectWithInjection(Context.java:489)
        at com.aws.greengrass.dependency.Context$Value.get(Context.java:436)
        at com.aws.greengrass.dependency.Context.get(Context.java:100)
        at com.aws.greengrass.lifecyclemanager.Kernel.parseArgs(Kernel.java:665)
        at com.aws.greengrass.easysetup.GreengrassSetup.performSetup(GreengrassSetup.java:301)
        at com.aws.greengrass.easysetup.GreengrassSetup.main(GreengrassSetup.java:274)
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
        at com.aws.greengrass.dependency.Context$Value.constructObjectWithInjection(Context.java:487)
        ... 5 more
Caused by: java.lang.IllegalArgumentException: configuration in services.aws.greengrass.Nucleus is already a leaf, cannot become a container
        at com.aws.greengrass.config.Topics.createInteriorChild(Topics.java:165)
        at com.aws.greengrass.config.Topics.createInteriorChild(Topics.java:151)
        at com.aws.greengrass.config.Topics.lookupTopics(Topics.java:233)
        at com.aws.greengrass.config.Topics.lookupTopics(Topics.java:219)
        at com.aws.greengrass.config.Configuration.lookupTopics(Configuration.java:86)
        at com.aws.greengrass.deployment.DeviceConfiguration.getTopics(DeviceConfiguration.java:768)
        at com.aws.greengrass.deployment.DeviceConfiguration.getLoggingConfigurationTopics(DeviceConfiguration.java:224)
        at com.aws.greengrass.deployment.DeviceConfiguration.handleLoggingConfig(DeviceConfiguration.java:443)
        at com.aws.greengrass.deployment.DeviceConfiguration.<init>(DeviceConfiguration.java:167)
        ... 11 more
```

**Environment**
 - OS: Windows 11 64 bit
 - JDK version: Amazon Correto 17
 - Nucleus version: 2.11.2

**Comment by vmyron** [comment]
Log file content

2023-09-28T10:37:40.171Z [INFO] (main) com.aws.greengrass.util.platforms.Platform: Getting platform instance com.aws.greengrass.util.platforms.windows.WindowsPlatform.. {}
2023-09-28T10:37:40.241Z [INFO] (main) com.aws.greengrass.lifecyclemanager.Kernel: No ongoing deployment detected. Proceed as default. {}
2023-09-28T10:37:40.244Z [WARN] (main) com.aws.greengrass.lifecyclemanager.KernelLifecycle: Transaction log C:\Tools\greengrass\config\config.tlog is invalid and no usable backup transaction log exists. Either an initial Nucleus setup is ongoing or all config tlogs were corrupted. {}
2023-09-28T10:37:40.244Z [INFO] (main) com.aws.greengrass.config.Configuration: config-loading. Read configuration from a file path. {path=C:\Tools\GreengrassInstaller\config.yaml}

**Comment by vmyron** [comment]
I've tried to change config.yaml
```
---
system:
  rootpath: "/greengrass"
services:
  aws.greengrass.Nucleus:
    version: "2.11.2"
  aws.greengrass.RegistrationPlugin:
```

And got following message in console
Default user creation is only supported on Linux platforms, Greengrass will not make a user for you. Ensure that the user exists and password is stored. Continuing...
Unable to set up Nucleus as a system service

Log file content is equal to previous try

**Comment by vmyron** [comment]
I've tried also following config
```
---
system:
  rootpath: "/greengrass"
services:
  aws.greengrass.Nucleus:
    componentType: "NUCLEUS"
    version: "2.11.2"
    configuration:
      mqtt:
        port: 443
      awsRegion: eu-central-1
  aws.greengrass.RegistrationPlugin:
    componentType: "PLUGIN"
    configuration:
      server:
        port: 8088
```
CMD response:
```
Default user creation is only supported on Linux platforms, Greengrass will not make a user for you. Ensure that the user exists and password is stored. Continuing...
Unable to set up Nucleus as a system service
```

Log file
```
2023-09-28T11:25:12.234Z [INFO] (main) com.aws.greengrass.util.platforms.Platform: Getting platform instance com.aws.greengrass.util.platforms.windows.WindowsPlatform.. {}
2023-09-28T11:25:12.305Z [INFO] (main) com.aws.greengrass.lifecyclemanager.Kernel: No ongoing deployment detected. Proceed as default. {}
2023-09-28T11:25:12.311Z [WARN] (main) com.aws.greengrass.lifecyclemanager.KernelLifecycle: Transaction log C:\Tools\greengrass\config\config.tlog is invalid and no usable backup transaction log exists. Either an initial Nucleus setup is ongoing or all config tlogs were corrupted. {}
2023-09-28T11:25:12.311Z [INFO] (main) com.aws.greengrass.config.Configuration: config-loading. Read configuration from a file path. {path=C:\Tools\GreengrassInstaller\config.yaml}

```

bootstrap.tlog
```
{"TS":1695900212047,"TP":["system","rootpath"],"W":"changed","V":"/greengrass"}
{"TS":1695900212047,"TP":["services","aws.greengrass.RegistrationPlugin","componentType"],"W":"changed","V":"PLUGIN"}
{"TS":1695900212047,"TP":["services","aws.greengrass.RegistrationPlugin","configuration","server","port"],"W":"changed","V":8088}
{"TS":1695900212047,"TP":["services","aws.greengrass.Nucleus","componentType"],"W":"changed","V":"NUCLEUS"}
{"TS":1695900212047,"TP":["services","aws.greengrass.Nucleus","version"],"W":"changed","V":"2.11.2"}
{"TS":1695900212047,"TP":["services","aws.greengrass.Nucleus","configuration","mqtt","port"],"W":"changed","V":443}
{"TS":1695900212047,"TP":["services","aws.greengrass.Nucleus","configuration","awsRegion"],"W":"changed","V":"eu-central-1"}
{"TS":1695900312305,"TP":["services","main","lifecycle"],"W":"interiorAdded","V":null} 
```

config.tlog
```
{"TS":1695900212047,"TP":["system","rootpath"],"W":"changed","V":"/greengrass"}
{"TS":1695900212047,"TP":["services","aws.greengrass.RegistrationPlugin","componentType"],"W":"changed","V":"PLUGIN"}
{"TS":1695900212047,"TP":["services","aws.greengrass.RegistrationPlugin","configuration","server","port"],"W":"changed","V":8088}
{"TS":1695900212047,"TP":["services","aws.greengrass.Nucleus","componentType"],"W":"changed","V":"NUCLEUS"}
{"TS":1695900212047,"TP":["services","aws.greengrass.Nucleus","version"],"W":"changed","V":"2.11.2"}
{"TS":1695900212047,"TP":["services","aws.greengrass.Nucleus","configuration","mqtt","port"],"W":"changed","V":443}
{"TS":1695900212047,"TP":["services","aws.greengrass.Nucleus","configuration","awsRegion"],"W":"changed","V":"eu-central-1"}
{"TS":1695900312305,"TP":["services","main","lifecycle"],"W":"interiorAdded","V":null}
{"TS":1,"TP":["services","main","dependencies"],"W":"changed","V":["aws.greengrass.Nucleus"]}
{"TS":1,"TP":["services","main","dependencies"],"W":"changed","V":["aws.greengrass.Nucleus"]}
{"TS":1695900312426,"TP":["services","aws.greengrass.Nucleus","configuration","logging"],"W":"interiorAdded","V":null}
{"TS":1,"TP":["services","aws.greengrass.Nucleus","configuration","componentStoreMaxSizeBytes"],"W":"changed","V":10000000000}
{"TS":1,"TP":["services","aws.greengrass.Nucleus","configuration","componentStoreMaxSizeBytes"],"W":"changed","V":10000000000}
{"TS":1,"TP":["services","aws.greengrass.Nucleus","configuration","deploymentPollingFrequencySeconds"],"W":"changed","V":15}
{"TS":1,"TP":["services","aws.greengrass.Nucleus","configuration","deploymentPollingFrequencySeconds"],"W":"changed","V":15}
{"TS":1695900312429,"TP":["services","aws.greengrass.Nucleus","configuration","runWithDefault"],"W":"interiorAdded","V":null}
{"TS":1695900312429,"TP":["services","aws.greengrass.Nucleus","configuration","runWithDefault","windowsUser"],"W":"changed","V":"ggc_user"}
{"TS":1695900312429,"TP":["services","aws.greengrass.Nucleus","configuration","runWithDefault","windowsUser"],"W":"changed","V":"ggc_user"}
{"TS":1695900312481,"TP":["services","aws.greengrass.Nucleus","configuration","platformOverride"],"W":"interiorAdded","V":null}
{"TS":1,"TP":["services","aws.greengrass.Nucleus","dependencies"],"W":"changed","V":null}
{"TS":1,"TP":["services","aws.greengrass.Nucleus","dependencies"],"W":"changed","V":[]}
{"TS":1,"TP":["services","aws.greengrass.Nucleus","lifecycle"],"W":"interiorAdded","V":null}
{"TS":1695900312502,"TP":["services","aws.greengrass.Nucleus","lifecycle","bootstrap"],"W":"interiorAdded","V":null}
{"TS":1695900312502,"TP":["services","aws.greengrass.Nucleus","lifecycle","bootstrap","requiresPrivilege"],"W":"changed","V":true}
{"TS":1695900312502,"TP":["services","aws.greengrass.Nucleus","lifecycle","bootstrap","requiresPrivilege"],"W":"changed","V":true}
{"TS":1695900312502,"TP":["services","aws.greengrass.Nucleus","lifecycle","bootstrap","script"],"W":"changed","V":"copy \"c:\\greengrass\\alts\\current\\distro\\bin\\greengrass.xml\" \"c:\\greengrass\\packages\\artifacts-unarchived\\aws.greengrass.Nucleus\\2.11.2\\aws.greengrass.nucleus\\bin\\greengrass.xml\"& del /q \"c:\\greengrass\\alts\\current\\*\"&& for /d %x in (\"c:\\greengrass\\alts\\current\\*\") do @rd /s /q \"%x\"&& echo {configuration:/jvmOptions} > \"c:\\greengrass\\alts\\current\\launch.params\"&& mklink /d \"c:\\greengrass\\alts\\current\\distro\" \"c:\\greengrass\\packages\\artifacts-unarchived\\aws.greengrass.Nucleus\\2.11.2\\aws.greengrass.nucleus\"&& exit 100"}
{"TS":1695900312502,"TP":["services","aws.greengrass.Nucleus","lifecycle","bootstrap","script"],"W":"changed","V":"copy \"c:\\greengrass\\alts\\current\\distro\\bin\\greengrass.xml\" \"c:\\greengrass\\packages\\artifacts-unarchived\\aws.greengrass.Nucleus\\2.11.2\\aws.greengrass.nucleus\\bin\\greengrass.xml\"& del /q \"c:\\greengrass\\alts\\current\\*\"&& for /d %x in (\"c:\\greengrass\\alts\\current\\*\") do @rd /s /q \"%x\"&& echo {configuration:/jvmOptions} > \"c:\\greengrass\\alts\\current\\launch.params\"&& mklink /d \"c:\\greengrass\\alts\\current\\distro\" \"c:\\greengrass\\packages\\artifacts-unarchived\\aws.greengrass.Nucleus\\2.11.2\\aws.greengrass.nucleus\"&& exit 100"}
{"TS":1695900312556,"TP":["setenv"],"W":"interiorAdded","V":null}
{"TS":0,"TP":["setenv","GGC_VERSION"],"W":"changed","V":"2.11.2"}
{"TS":0,"TP":["setenv","GGC_VERSION"],"W":"changed","V":"2.11.2"} 
```

**Comment by MikeDombo** [comment]
Hello,

You provided the option `--trusted-plugin "C:\Tools\GreengrassPlugins\aws.greengrass.MyCustomProvisioningPlugin"`. This needs to be a jar file ending with `.jar`. 


Please fix that and try again. I'd recommend that you start from the fleet provisioning plugin as an example of how to implement the logic: https://github.com/aws-greengrass/aws-greengrass-fleet-provisioning-by-claim

**Comment by vmyron** [comment]
Hi @MikeDombo 
Thanks for your response

It was a typo in message. I've fixed it.
-Droot and rootpath are matching

**Comment by MikeDombo** [comment]
With the correct configuration and command, please run again.

**Comment by vmyron** [comment]
Oh. Thanks for this clarification.
I was wondering because effectiveConfig doesn't contain correct values. But when I've checked config.tlog, it contains correct changes.

Than you again.

**Comment by MikeDombo** [comment]
Yes, Greengrass only updates effective config when it starts and stops, not while it is running.

Glad you got it working.
