### ISSUE TITLE
Installation doesn't work from behind a proxy

### ISSUE THREAD

**Issue by skel84** [aws-greengrass/aws-greengrass-nucleus#854]
Hi, 

I'm trying to run the installation from behind a corporate proxy. 
- From this box, I am only allowed to reach the internet through an http proxy. 
- Also name resolution happens through the proxy. 
- I managed to make SQS work though the proxy

Using a custom init-config and all the operations that are using the aws sdk are working, but it fails when it's trying to download the rootCA. That part of the install script is using the java.net and java.nio and apparently they don't use the proxy: https://github.com/aws-greengrass/aws-greengrass-nucleus/blob/4da4e9b7feed8ef7b4e2037fa24add3dc67c3137/src/main/java/com/aws/greengrass/easysetup/DeviceProvisioningHelper.java#L285

I've also tried to specify `-Djava.net.useSystemProxies=true` but still it doesn't work. Here is the log:

```
sudo -E java -Djava.net.useSystemProxies=true  -Droot="/greengrass/v2" -Dlog.store=FILE -jar ./GreengrassCore/lib/Greengrass.jar --aws-region eu-central-1 --thing-name GreengrassQuickStartCore-177876a9adf --thing-group-name GreengrassQuickStartGroup --component-default-user ggc_user:ggc_group --provision true --setup-system-service true --deploy-dev-tools true --init-config /tmp/effectiveConfig.yaml
Added ggc_user to ggc_group
Provisioning AWS IoT resources for the device with IoT Thing Name: [GreengrassQuickStartCore-177876a9adf]...
Found IoT policy "GreengrassV2IoTThingPolicy", reusing it
Creating keys and certificate...
Attaching policy to certificate...
Creating IoT Thing "GreengrassQuickStartCore-177876a9adf"...
Attaching certificate to IoT thing...
Successfully provisioned AWS IoT resources for the device with IoT Thing Name: [GreengrassQuickStartCore-177876a9adf]!
Adding IoT Thing [GreengrassQuickStartCore-177876a9adf] into Thing Group: [GreengrassQuickStartGroup]...
IoT Thing Group "GreengrassQuickStartGroup" already existed, reusing it
Successfully added Thing into Thing Group: [GreengrassQuickStartGroup]
Setting up resources for aws.greengrass.TokenExchangeService ...
Attaching TES role policy to IoT thing...
IAM policy named "GreengrassV2TokenExchangeRoleAccess" already exists. Please attach it to the IAM role if not already
Configuring Nucleus with provisioned resource details...
Downloading Root CA from "https://www.amazontrust.com/repository/AmazonRootCA1.pem"
Error while trying to setup Greengrass Nucleus
java.net.UnknownHostException: www.amazontrust.com
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:607)
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:284)
        at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
        at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
        at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1570)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
        at java.net.URL.openStream(URL.java:1068)
        at com.aws.greengrass.easysetup.DeviceProvisioningHelper.downloadFileFromURL(DeviceProvisioningHelper.java:286)
        at com.aws.greengrass.easysetup.DeviceProvisioningHelper.downloadRootCAToFile(DeviceProvisioningHelper.java:278)
        at com.aws.greengrass.easysetup.DeviceProvisioningHelper.updateKernelConfigWithIotConfiguration(DeviceProvisioningHelper.java:310)
        at com.aws.greengrass.easysetup.GreengrassSetup.provision(GreengrassSetup.java:425)
        at com.aws.greengrass.easysetup.GreengrassSetup.performSetup(GreengrassSetup.java:294)
        at com.aws.greengrass.easysetup.GreengrassSetup.main(GreengrassSetup.java:242)
```

**Comment by MikeDombo** [comment]
Hi Francesco,
We will have instructions going up soon in our documentation for manually setting up Greengrass, including behind a proxy. Those instructions will walk you through the whole process including manually downloading the Amazon Root CA so that you aren't relying on the Nucleus to self-provision, which is difficult to do behind a proxy.

**Comment by MikeDombo** [comment]
I will also look at some code changes to use the proxy configuration to download the root CA, however that won't unblock you immediately.

**Comment by MikeDombo** [comment]
Setting the Java system properties `-Dhttp.proxyHost=<host> -Dhttp.proxyPort=<port>` may also solve the issue. See: https://docs.oracle.com/javase/8/docs/technotes/guides/net/proxies.html

**Comment by skel84** [comment]
> Setting the Java system properties `-Dhttp.proxyHost=<host> -Dhttp.proxyPort=<port>` may also solve the issue. See: https://docs.oracle.com/javase/8/docs/technotes/guides/net/proxies.html

tried that already and it didn't help

> Hi Francesco,
> We will have instructions going up soon in our documentation for manually setting up Greengrass, including behind a proxy. Those instructions will walk you through the whole process including manually downloading the Amazon Root CA so that you aren't relying on the Nucleus to self-provision, which is difficult to do behind a proxy.
> I will also look at some code changes to use the proxy configuration to download the root CA, however that won't unblock you immediately.

That's great! It would be nice to also have the code changes so that everything could be done with just the easy installer

**Comment by MikeDombo** [comment]
Did you also try `-Dhttps.proxyHost`? Using `https` instead of `http`.

**Comment by skel84** [comment]
yes I've tried that too

**Comment by MikeDombo** [comment]
OK then, thank you for verifying
