### ISSUE TITLE
(com.aws.greengrass.util.orchestration.SystemdUtils): Greengrass Nucleus Fails to start in WSL

### ISSUE THREAD

**Issue by mirgj** [aws-greengrass/aws-greengrass-nucleus#891]
**Describe the bug**
When executing Greengrass configuration inside Windows Linux Subsystem (WSL) it fails to start with the following error: **Unable to setup Nucleus as system service**

**To Reproduce**

- Install WSL (Ubuntu 20.04) on Windows Server 2019 [link](https://docs.microsoft.com/en-us/windows/wsl/install-manual)
- Install Java environment on WSL
- Configure AWS credentials (as [described here](https://docs.aws.amazon.com/greengrass/v2/developerguide/quick-installation.html) )
- Download and install GeenGrass Nucleus (as [described here](https://docs.aws.amazon.com/greengrass/v2/developerguide/quick-installation.html#download-greengrass-core-v2) )
```
sudo -E java -Droot="/greengrass/v2" -Dlog.store=FILE \
  -jar ./GreengrassCore/lib/Greengrass.jar \
  --aws-region us-east-1 \
  --thing-name GreengrassQuickStartCore-[id] \
  --thing-group-name GreengrassQuickStartGroup \
  --tes-role-name GGProvisioningRole \
  --tes-role-alias-name GGProvisioningRoleAlias \
  --component-default-user ggc_user:ggc_group \
  --provision true \
  --setup-system-service true
```

**Expected behavior**
It should start the service successfully

**Actual behavior**
Fail to start with error: **Unable to setup Nucleus as system service**

**Environment**
 - OS: Windows Linux Subsystem (Ubuntu 20.04) on Windows Server 2019
 - JDK version: 11
 - Nucleus version: 2.0.5

**Additional context**
GreenGrass error logs:

```
2021-03-12T03:45:16.804Z [ERROR] (Copier) com.aws.greengrass.util.orchestration.SystemdUtils: systemd-setup. {stderr=System has not been booted with systemd as init system (PID 1). Can't operate., command=systemctl daemon-reload}
2021-03-12T03:45:16.805Z [ERROR] (Copier) com.aws.greengrass.util.orchestration.SystemdUtils: systemd-setup. {stderr=Failed to connect to bus: Host is down, command=systemctl daemon-reload}
2021-03-12T03:45:16.807Z [ERROR] (main) com.aws.greengrass.util.orchestration.SystemdUtils: systemd-setup. Failed to set up systemd service. {}
java.io.IOException: Command systemctl daemon-reload failed
        at com.aws.greengrass.util.orchestration.SystemdUtils.runCommand(SystemdUtils.java:87)
        at com.aws.greengrass.util.orchestration.SystemdUtils.setupSystemService(SystemdUtils.java:46)
        at com.aws.greengrass.easysetup.GreengrassSetup.performSetup(GreengrassSetup.java:299)
        at com.aws.greengrass.easysetup.GreengrassSetup.main(GreengrassSetup.java:242)
```

**Comment by MikeDombo** [comment]
If you remove the `--setup-system-service true` then it will be able to provision and start. The problem is that your WSL isn't setup using systemd as the error from systemctl says `System has not been booted with systemd as init system (PID 1). Can't operate.`
This seems to be a known issue with WSL: https://github.com/MicrosoftDocs/WSL/issues/457.

Once you've provisioned you will then want to manually configure to run Greengrass as a system service by calling the script located at `<gg root>/alts/current/distro/bin/loader`

**Comment by MikeDombo** [comment]
If you do find an acceptable solution, please report back here and we can see about adding it either in documentation or into the code itself.
