### ISSUE TITLE
Lambda Python logger: traceback prints are cluttered with additional text

### ISSUE THREAD

**Issue by Lard4** [aws-greengrass/aws-greengrass-nucleus#947]
**Describe the bug**
When a user calls any traceback library function, the GG logger heavily pollutes the output.

**To Reproduce**
call traceback.print_stack() from a lambda component.

**Expected behavior**
It should log a clear, readable stacktrace.

**Actual behavior**
It looks like this when you call `traceback.print_exc(); traceback.print_stack()`
```
2021-04-27T21:54:07.372Z [ERROR] (pool-2-thread-31) TestGPSLambda: traceback.py:105,Traceback (most recent call last):. {serviceInstance=0, serviceName=TestGPSLambda, currentState=RUNNING}
2021-04-27T21:54:07.372Z [ERROR] (pool-2-thread-31) TestGPSLambda: {serviceInstance=0, serviceName=TestGPSLambda, currentState=RUNNING}
2021-04-27T21:54:07.377Z [ERROR] (pool-2-thread-31) TestGPSLambda: traceback.py:105,. {serviceInstance=0, serviceName=TestGPSLambda, currentState=RUNNING}
2021-04-27T21:54:07.378Z [ERROR] (pool-2-thread-31) TestGPSLambda: traceback.py:105,  File "/lambda/lambda_function.py", line 32, in on_stream_event. {serviceInstance=0, serviceName=TestGPSLambda, currentState=RUNNING}
2021-04-27T21:54:07.378Z [ERROR] (pool-2-thread-31) TestGPSLambda:     self.send_to_iot_core(message_string). {serviceInstance=0, serviceName=TestGPSLambda, currentState=RUNNING}
2021-04-27T21:54:07.379Z [ERROR] (pool-2-thread-31) TestGPSLambda: {serviceInstance=0, serviceName=TestGPSLambda, currentState=RUNNING}
2021-04-27T21:54:07.380Z [ERROR] (pool-2-thread-31) TestGPSLambda: traceback.py:105,. {serviceInstance=0, serviceName=TestGPSLambda, currentState=RUNNING}
2021-04-27T21:54:07.383Z [ERROR] (pool-2-thread-31) TestGPSLambda: traceback.py:105,  File "/lambda/lambda_function.py", line 59, in send_to_iot_core. {serviceInstance=0, serviceName=TestGPSLambda, currentState=RUNNING}
2021-04-27T21:54:07.383Z [ERROR] (pool-2-thread-31) TestGPSLambda:     future.result(TIMEOUT). {serviceInstance=0, serviceName=TestGPSLambda, currentState=RUNNING}
2021-04-27T21:54:07.384Z [ERROR] (pool-2-thread-31) TestGPSLambda: {serviceInstance=0, serviceName=TestGPSLambda, currentState=RUNNING}
2021-04-27T21:54:07.385Z [ERROR] (pool-2-thread-31) TestGPSLambda: traceback.py:105,. {serviceInstance=0, serviceName=TestGPSLambda, currentState=RUNNING}
2021-04-27T21:54:07.389Z [ERROR] (pool-2-thread-31) TestGPSLambda: traceback.py:105,  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 434, in result. {serviceInstance=0, serviceName=TestGPSLambda, currentState=RUNNING}
2021-04-27T21:54:07.389Z [ERROR] (pool-2-thread-31) TestGPSLambda:     raise TimeoutError(). {serviceInstance=0, serviceName=TestGPSLambda, currentState=RUNNING}
2021-04-27T21:54:07.389Z [ERROR] (pool-2-thread-31) TestGPSLambda: {serviceInstance=0, serviceName=TestGPSLambda, currentState=RUNNING}
2021-04-27T21:54:07.391Z [ERROR] (pool-2-thread-31) TestGPSLambda: traceback.py:105,. {serviceInstance=0, serviceName=TestGPSLambda, currentState=RUNNING}
2021-04-27T21:54:07.394Z [ERROR] (pool-2-thread-31) TestGPSLambda: traceback.py:105,concurrent.futures._base.TimeoutError. {serviceInstance=0, serviceName=TestGPSLambda, currentState=RUNNING}
2021-04-27T21:54:07.394Z [ERROR] (pool-2-thread-31) TestGPSLambda: {serviceInstance=0, serviceName=TestGPSLambda, currentState=RUNNING}
2021-04-27T21:54:07.397Z [ERROR] (pool-2-thread-31) TestGPSLambda: traceback.py:105,. {serviceInstance=0, serviceName=TestGPSLambda, currentState=RUNNING}
2021-04-27T21:54:07.400Z [ERROR] (pool-2-thread-31) TestGPSLambda: traceback.py:25,  File "/usr/local/lib/python3.7/dist-packages/awscrt/eventstream/rpc.py", line 627, in _on_continuation_message. {serviceInstance=0, serviceName=TestGPSLambda, currentState=RUNNING}
2021-04-27T21:54:07.400Z [ERROR] (pool-2-thread-31) TestGPSLambda:     flags=flags). {serviceInstance=0, serviceName=TestGPSLambda, currentState=RUNNING}
2021-04-27T21:54:07.401Z [ERROR] (pool-2-thread-31) TestGPSLambda: {serviceInstance=0, serviceName=TestGPSLambda, currentState=RUNNING}
2021-04-27T21:54:07.402Z [ERROR] (pool-2-thread-31) TestGPSLambda: traceback.py:25,. {serviceInstance=0, serviceName=TestGPSLambda, currentState=RUNNING}
2021-04-27T21:54:07.405Z [ERROR] (pool-2-thread-31) TestGPSLambda: traceback.py:25,  File "/usr/local/lib/python3.7/dist-packages/awsiot/eventstreamrpc.py", line 804, in on_continuation_message. {serviceInstance=0, serviceName=TestGPSLambda, currentState=RUNNING}
2021-04-27T21:54:07.405Z [ERROR] (pool-2-thread-31) TestGPSLambda:     self.operation._on_continuation_message(*args, **kwargs). {serviceInstance=0, serviceName=TestGPSLambda, currentState=RUNNING}
2021-04-27T21:54:07.405Z [ERROR] (pool-2-thread-31) TestGPSLambda: {serviceInstance=0, serviceName=TestGPSLambda, currentState=RUNNING}
2021-04-27T21:54:07.406Z [ERROR] (pool-2-thread-31) TestGPSLambda: traceback.py:25,. {serviceInstance=0, serviceName=TestGPSLambda, currentState=RUNNING}
2021-04-27T21:54:07.408Z [ERROR] (pool-2-thread-31) TestGPSLambda: traceback.py:25,  File "/usr/local/lib/python3.7/dist-packages/awsiot/eventstreamrpc.py", line 711, in _on_continuation_message. {serviceInstance=0, serviceName=TestGPSLambda, currentState=RUNNING}
2021-04-27T21:54:07.408Z [ERROR] (pool-2-thread-31) TestGPSLambda:     self._handle_data(model_name, payload). {serviceInstance=0, serviceName=TestGPSLambda, currentState=RUNNING}
2021-04-27T21:54:07.409Z [ERROR] (pool-2-thread-31) TestGPSLambda: {serviceInstance=0, serviceName=TestGPSLambda, currentState=RUNNING}
2021-04-27T21:54:07.410Z [ERROR] (pool-2-thread-31) TestGPSLambda: traceback.py:25,. {serviceInstance=0, serviceName=TestGPSLambda, currentState=RUNNING}
2021-04-27T21:54:07.412Z [ERROR] (pool-2-thread-31) TestGPSLambda: traceback.py:25,  File "/usr/local/lib/python3.7/dist-packages/awsiot/eventstreamrpc.py", line 753, in _handle_data. {serviceInstance=0, serviceName=TestGPSLambda, currentState=RUNNING}
2021-04-27T21:54:07.412Z [ERROR] (pool-2-thread-31) TestGPSLambda:     self._stream_handler.on_stream_event(shape). {serviceInstance=0, serviceName=TestGPSLambda, currentState=RUNNING}
2021-04-27T21:54:07.412Z [ERROR] (pool-2-thread-31) TestGPSLambda: {serviceInstance=0, serviceName=TestGPSLambda, currentState=RUNNING}
2021-04-27T21:54:07.414Z [ERROR] (pool-2-thread-31) TestGPSLambda: traceback.py:25,. {serviceInstance=0, serviceName=TestGPSLambda, currentState=RUNNING}
2021-04-27T21:54:07.416Z [ERROR] (pool-2-thread-31) TestGPSLambda: traceback.py:25,  File "/lambda/lambda_function.py", line 35, in on_stream_event. {serviceInstance=0, serviceName=TestGPSLambda, currentState=RUNNING}
2021-04-27T21:54:07.416Z [ERROR] (pool-2-thread-31) TestGPSLambda:     traceback.print_stack(). {serviceInstance=0, serviceName=TestGPSLambda, currentState=RUNNING}
2021-04-27T21:54:07.416Z [ERROR] (pool-2-thread-31) TestGPSLambda: {serviceInstance=0, serviceName=TestGPSLambda, currentState=RUNNING}
2021-04-27T21:54:07.418Z [ERROR] (pool-2-thread-31) TestGPSLambda: traceback.py:25,. {serviceInstance=0, serviceName=TestGPSLambda, currentState=RUNNING}
```

**Environment**
 - OS: Raspbian
 - JDK version: irrelevant
 - Python version: 3.7
 - Nucleus version: 2.1.0

**Additional context**
You can't even begin to decipher exception tracebacks. This is very bad.

**Comment by MikeDombo** [comment]
Hi Kevin,
Thank you for your feedback. We are using a standardized logging format across all our Greengrass loggers and so we will not be making any changes to the format. 

You have several options however to make things easier. 

- You could use a command like `cat <component>.log | cut -d " " -f5-` which will give you the messages and everything after it.
- You could change the logging format from TEXT mode to JSON mode in the Nucleus component's configuration. Then you can use `cat <component>.log | jq -s '.message'` to extract the message field from each line.
- Finally, you could log to your own file using a Python logger if you wish.

**Comment by Lard4** [comment]
Sure that kind of works. But, I think the standard format should be much better. If I do `print("line1 \n line2` then why is this logged as:
```
2021-04-28T05:52:54.254Z [ERROR] (pool-2-thread-26) TestGPSLambda: traceback.py:1, line1!. {serviceInstance=0, serviceName=TestGPSLambda, currentState=RUNNING}
2021-04-28T05:52:54.254Z [ERROR] (pool-2-thread-26) TestGPSLambda: line2. {serviceInstance=0, serviceName=TestGPSLambda, currentState=RUNNING}
```

I would expect that the formatting be more sensical, especially for things like stack traces which are highly visual logs. Having the `\n\t` **not** re-print the log line header is wonderfully common.

**Comment by MikeDombo** [comment]
Yes I can see how that would make sense, but that isn't possible to do. We cannot know that you're using a single print statement or multiples, all that Greengrass sees is a stream of characters with occasional newlines in there. Therefore, all that we can do is to split on the newline characters.

**Comment by Lard4** [comment]
Oh, got it. Good to know!
